#! /bin/sh

test -d build-aux || mkdir build-aux

# autoreconf seems to be missing the fact that libtool is used if
# the macros are not defined first.  So help it.
test -f ltmain.sh || libtoolize --install --force

autoreconf --force --verbose --install
